### ISSUE TITLE
ruby-1.8.6ではsrc_bcdice/TableFileData.rbのgetTableDataFromFile()が動かない

### ISSUE THREAD

**Issue by shiracha** [torgtaitai/DodontoF#21]
これは作業中に気づいたんですが直してなかったのでissueの起票だけ。
# 問題概要

`TableFileData::getTableDataFromFile()` は内部的に
`&:symbol` 形式の `Proc` オブジェクト生成を行って、これを使って処理を書いている部分があります。
しかし1.8系にこの機能は有りません。
# 修正案
## 1. 1.8.6のサポートを打ち切る

オススメです。
ruby的に1.8系列は2014年7月31日に(Herokuの助力で6か月終了を伸ばしたうえで)サポート終了しており
(それどころか実は2.0.0もサポートは終了してしまっており... https://www.ruby-lang.org/ja/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)
その後いくつものセキュリティパッチがあったんですが、1.8系には取り込まれていないので単純に使うと危険なので……。
(DodontoFServerを動かすとこにどれくらいのセキュリティが求められるかというのはもちろんありますが。
またDodontoF自体がエラーを生んでるというよりもruby1.8を入れてるサーバの脆弱性ではあるので。)
## 2. 以下のpatchを当てる

単純に技術的には以下で解決します。

``` diff
diff --git a/src_bcdice/TableFileData.rb b/src_bcdice/TableFileData.rb
index 6f4d2b5..5cf866d 100644
--- a/src_bcdice/TableFileData.rb
+++ b/src_bcdice/TableFileData.rb
@@ -131,7 +131,8 @@ class TableFileData

   def getTableDataFromFile(fileName)
     table = []
-    lines = File.read(fileName).toutf8.lines.map(&:chomp)
+    lines = File.read(fileName).toutf8.lines.map { |s| s.chomp }

     defineLine = lines.shift
     dice, title = getDiceAndTitle(defineLine)
```

**Comment by shiracha** [comment]
ちなみに同様の問題は `git grep "&:"` で検出でき、筆禍掛かったのは以下の通りです

```sh
src_bcdice/TableFileData.rb:    lines = File.read(fileName).toutf8.lines.map(&:chomp)
src_bcdice/test/DiceBotTest.rb:      errorLog = $RUBY18_WIN ? @errorLog.map(&:tosjis) : @errorLog
src_bcdice/test/DiceBotTest.rb:        map(&:chomp)
src_bcdice/test/DiceBotTestData.rb:    input = matches[1].lines.map(&:chomp)
src_bcdice/test/DiceBotTestData.rb:      m.captures.map(&:to_i)
src_ruby/mysql.rb:    query(db ? "show databases like '#{db}'" : "show databases").map(&:first)
src_ruby/mysql.rb:    query(q).map(&:first)
src_ruby/ruby-mysql/mysql.rb:    query(db ? "show databases like '#{db}'" : "show databases").map(&:first)
src_ruby/ruby-mysql/mysql.rb:    query(q).map(&:first)
```

**Comment by shiracha** [comment]
あ。ちなみに 1.8."7" では動きます。(1.8.7から `Symbol#to_proc` が入ったので)

**Comment by torgtaitai** [comment]
すみません、こちらまたCLOSEしておりませんでした。
自分の中では
＞1. 1.8.6のサポートを打ち切る
断然これですね。
レガシーフリーな世の中で生きていきたいです。
というわけで、今回でREADMEを書き換えておきました。
