### ISSUE TITLE
バージョンごとのタグ付けの提案

### ISSUE THREAD

**Issue by ochaochaocha3** [torgtaitai/DodontoF#25]
最近のリファクタリングでコミット数が増えたため、リリース時のコミットが埋もれがちになってきました。そこで、GitHubの他のリポジトリと同様、リリース時にコミットへのタグを付けてみてはいかがでしょうか？

例えば、以下のようなコマンドで行うことができます。

```bash
# リリース分のコミットが終わったときに
git tag v1.48.00

# コミットを指定することも可能
git tag v1.47.24 94c3c04

# GitHub にタグをアップロードする
git push --tags origin master
```

また、GitHubではリリース（≒タグ、リポジトリトップの上部の「Releases」）ごとにソースコードと別にバイナリファイルをアップロードすることができます。これを利用すると、リポジトリ中に重い .swf ファイルを含めず、アップロードするバイナリファイル（例えばどどんとふ公式で配布している .zip のアーカイブ）にのみ含めることができます。このようにしてリポジトリの軽量化を行うのはいかがでしょうか？

**Comment by ochaochaocha3** [comment]
対応ありがとうございます。.swf がソースから抜けたのはやはり効果的ですね。Pull時の差分のダウンロードがかなり速くなりました。

**Comment by torgtaitai** [comment]
こちらこそ指摘ありがとうございます。
これで良いのかと悪戦苦闘しておりました。

**Comment by ochaochaocha3** [comment]
この形で大丈夫だと思います。一例を示しますと、GitBucket（[gitbucket/gitbucket](https://github.com/gitbucket/gitbucket)）の[リリース](https://github.com/gitbucket/gitbucket/releases)は、同様にタグ（こちらではリリースノートも）・バイナリ・ソースコードが一つの場所に固まっていて便利でした。
