### ISSUE TITLE
[Question] DodontoF.swf のgithub提供が無くなった理由と対応について

### ISSUE THREAD

**Issue by Chiether** [torgtaitai/DodontoF#37]
先ほど git --rebase したところ DodontoF.swf が削除されサービスが提供できなくなりました。
調べたところ f9ecb751340e064b48ed2c670244c63a2cebf2df で削除されたようですが、パッケージとの差分は意図的なものでしょうか。
というのもパッケージ版を確認したところ
index.htmlで指定されているembedタグのsrc属性はそのままで、
DodontoF.swfが同梱されていました。

もしかして今後は、tagに対応したパッケージの方から
DodontoF.swfだけを取り込むという運用か。
あるいは、各々コンパイルする方式で行うということでしょうか。

**Comment by torgtaitai** [comment]
＞もしかして今後は、tagに対応したパッケージの方から
＞DodontoF.swfだけを取り込むという運用か。
＞あるいは、各々コンパイルする方式で行うということでしょうか。

YES.その通りです。
swfが含まれているとリリース差分の取得に時間がかかりすぎるので、
技術的に明るい人しか使わないことが期待できるGithubではバイナリの直接コミットは止めた方が良い、
という提案を ochaochaocha3 さんからいただきまして、確かにその通りと納得したのでこのような方式に変わりました。

**Comment by Chiether** [comment]
なるほど。コミットログから消えた経緯がわかりませんでしたが。
確かにバイナリの直接コミットは、あまりメリットもありませんね。
一瞬驚いてしまいましたが、私もそれがよいと思います。ご回答ありがとうございました。

**Comment by ochaochaocha3** [comment]
提案いたしました ocha です。この件については issue #25 で提案を行いましたので、よろしければご参照ください。
