### ISSUE TITLE
どどんとふの配布をGithub releases にしてはどうか

### ISSUE THREAD

**Issue by raa0121** [torgtaitai/DodontoF#57]
Github には、バージョンごとにソースやビルド済みバイナリを圧縮ファイルで配布する機能があります。
ref: https://github.com/neovim/neovim/releases
マークダウンで情報も記載でき、Github でホスティングすることで www.dodontof.com の負荷を減らせる想定です。

いかがでしょうか。

**Comment by ochaochaocha3** [comment]
:+1: 
どどんとふ公式が落ちた場合のミラーにもなり得るので、賛成です。

**Comment by raa0121** [comment]
すでにやったっぽいので、閉じます
