### ISSUE TITLE
Chinese-Traditional.txt FIX

### ISSUE THREAD

**Issue by zeteticl** [torgtaitai/DodontoF#60]
fix the 
Server directory "language" files has problem. please change language file.

Language data has different,
before:
after:Chinese-Traditional

diff length before:972, after:971
diff item
before: "chatPalletDeleteTab"
   after: "chatPalletEdit"

and 
add some string DiceBotName

https://drive.google.com/file/d/0BzpM4z9_kUseRlJiQ3dJOEphcUU/view?usp=sharing

**Comment by torgtaitai** [comment]
Thank you for your help!
