### ISSUE TITLE
the chat.html do not work well

### ISSUE THREAD

**Issue by zeteticl** [torgtaitai/DodontoF#61]
http://www.hktrpg.com/DodontoF/chat.html
it cant get the chat log
but i dont know why does it happenT_T

**Comment by ochaochaocha3** [comment]
Select the room from the "RoomNo." drop-down list (and enter the password if required), then push the "入室" (Enter) button.
Your chat log seems to be recorded. (e.g. [Room 0](http://www.hktrpg.com/DodontoF/chat.html?r=0))
