### ISSUE TITLE
リリースファイルでGemfileが消えている

### ISSUE THREAD

**Issue by ochaochaocha3** [torgtaitai/DodontoF#76]
リポジトリとリリースファイルを比較していて気づいたのですが、リリースファイルではGemfileが**意図的に**削除されているのでしょうか？ もしそうでしたら、Gemfileの削除処理は行わないでいただきたいです。

Gemfileが存在すれば、Rubyの新しいバージョン移行に伴いライブラリを入れ直さなければならないとき（例：TRPG.NETサーバでは、2.3.1→2.4.1のときにこのようになりました）でも、必要なライブラリのインストールを `bundle install` というコマンドによって自動で行うことができます。msgpackだけとはいえ、**何のライブラリが必要か考えずに実行できる**のが非常に便利です。

**Comment by torgtaitai** [comment]
いえ、意図的ではないです。作業ミスで消してしまっていました。直しておきます。

**Comment by ochaochaocha3** [comment]
お手数かけてすみません。ありがとうございます。

**Comment by ochaochaocha3** [comment]
#79 のスクリプトでGemfileをアーカイブに含めることができたので、こちらは閉じます。
