### ISSUE TITLE
リリースファイルの生成手順について

### ISSUE THREAD

**Issue by ochaochaocha3** [torgtaitai/DodontoF#77]
#76 と関連することです。どどんとふのリポジトリとリリースファイルのディレクトリ構成は異なっていますが、リリースファイルの生成手順は公開できませんでしょうか？

必要性を感じた理由は以下のとおりです。

* **リリースファイルの生成手順が明らかになっていると新しい（まっさらな）環境を作りやすい。**
    * ダイスボット追加等の作業で一時的に含まれている可能性がある余分なファイルがなくなるため、現在リリースされているバージョンとの挙動の差を正しく調べやすくなると考えられます。
* **BCDiceのバージョンの同期を行いやすくなる。**
    * 現在、Onset!等と同様にBCDiceをサブモジュール化する作業を行っており、これが完了すればダイスボットの更新のマージが楽になります。また、そのマージのコマンドをリリースファイルの生成手順に入れ、自動化すれば更新ミスが非常に起こりにくくなります。

もし生成スクリプトのようなものがございましたら、同様の手順を `rake package` のようなコマンドで実行できるようにRakefileに移植できないかと考えています。ご検討よろしくお願いいたします。

**Comment by torgtaitai** [comment]
自前のリリースファイルの生成は完全に自分のローカル環境に割り切った作り方をしてしまっているため、
残念ながら簡単には公開できない形になってしまいっています。
この用途であれば、ディレクトリを移動するなどしてリポジトリからリリースファイルを作る簡易スクリプトを別途でっち上げたほうが早い気はします。
あるいは、一方に合わせこんでしまうか。

**Comment by ochaochaocha3** [comment]
ありがとうございます。リポジトリとリリースファイルの差を詳しく調べてみて、スクリプトにできそうでしたらまた提案したいと思います。
